plugins {
    id 'org.moddingx.modgradle.meta' version '5.0.3'
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

var dev = System.getenv('IS_DEV')?.toBoolean() ?: false
var releaseType = 'beta'
var baseVersion = '21.1'
var modBaseVersion = '1.21-4.0'
var cherishedWorldsVersion = 'o5lwJaRU' // 10.1.1+1.21.1

mod.configure {
    modid 'simplebackups'
    group 'de.melanx'
    versioning {
        if (dev) {
            def gitCommitHash = ['git', 'rev-parse', 'HEAD'].execute().text.trim()
            constant modBaseVersion + (gitCommitHash ? "-${gitCommitHash}" : '')
        } else {
            base modBaseVersion
            maven 'https://maven.melanx.de/release'
        }
    }

    neoforge "${baseVersion}.115"

    license 'The Apache License, Version 2.0'
    github 'ChaoticTrials/SimpleBackups'

    artifacts {
        sources {
            publishToRepositories()
        }
    }

    changelog {
        def lines = defaultChangelog.toString().split('\n')
        def filteredChangelog = lines.findAll { !it.startsWith('- [[meta]') }.join('\n')

        return filteredChangelog
    }


    publishing {
        maven {
            name 'melanx'
            url 'https://maven.melanx.de/release'
            credentials(PasswordCredentials)
        }
    }

    upload {
        all {
            type releaseType
            version '1.21.1'
            version '1.21.2'
            version '1.21.3'
            version '1.21.4'
            optional 'cherished-worlds'
        }
        curseforge {
            projectId 583228
        }
        modrinth {
            projectId 'fzSKSXVK'
        }
    }
}

dependencies {
    implementation "maven.modrinth:cherished-worlds:${cherishedWorldsVersion}"
}
