plugins {
    id 'org.moddingx.modgradle.meta' version '5.0.3'
}

var dev = System.getenv('IS_DEV')?.toBoolean() ?: false
var releaseType = 'release'
var baseVersion = '21.6'
mod.configure {
    modid 'simplebackups'
    group 'de.melanx'
    versioning {
        if (dev) {
            def gitCommitHash = ['git', 'rev-parse', 'HEAD'].execute().text.trim()
            constant baseVersion + (gitCommitHash ? "-${gitCommitHash}" : '')
        } else {
            base baseVersion
            maven 'https://maven.melanx.de/release'
        }
    }

    neoforge "${baseVersion}.8-beta"

    license 'The Apache License, Version 2.0'
    github 'ChaoticTrials/SimpleBackups'

    artifacts {
        sources {
            publishToRepositories()
        }
    }

    changelog {
        def lines = defaultChangelog.toString().split('\n')
        def filteredChangelog = lines.findAll { !it.startsWith('- [[meta]') }.join('\n')

        return filteredChangelog
    }


    publishing {
        maven {
            name 'melanx'
            url 'https://maven.melanx.de/release'
            credentials(PasswordCredentials)
        }
    }

    upload {
        all {
            type releaseType
            version '1.21.6'
            version '1.21.7'
            version '1.21.8'
        }
        curseforge {
            projectId 583228
        }
        modrinth {
            projectId 'fzSKSXVK'
        }
    }
}
