# Modified by the Simple Backups Fabric project in 2026.
# This file was adapted from upstream SimpleBackups for the Fabric platform.
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.19
fabric_api_version=0.158.0+26.2
forge_config_api_port_version=26.2.1

mod_version=26.2.1
maven_group=de.melanx
archives_base_name=simplebackups-fabric
