org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.1
loader_version=0.19.3
loom_version=1.17.19
fabric_api_version=0.149.1+26.1.2
forge_config_api_port_version=26.1.5

mod_version=26.1.5
maven_group=de.melanx
archives_base_name=simplebackups-fabric
